### PR TITLE
Adding toText to Value and Type

### PR DESCRIPTION
**Pull request by Gekctek**

### CODE REVIEW

**Comment by Gekctek** [comment]
@fermartz This is the start of the work for #5 
Right now I just have the `Value.toText(...)` implemented. I want to do the Types as well
Im basing my text off of the candid reference: https://internetcomputer.org/docs/current/references/candid-ref
If you look at the `ValueTests.mo` you can see the expected outputs for each value and at the end there is the advanced options
A mapper that gives you an unknown tag hash value and returns a Text if there is a mapping, otherwise return null
A function to override toText for specific values. if null is returned, will use default
```
tagHashMapper = ?(
    func(h : Hash.Hash) : ?Text {
        switch (h) {
            case (3) ?"\"hello\"";
            case (_) null;
        };
    },
);
toTextOverride = ?(
    func(v : Value.Value) : ?Text {
        switch (v) {
            // Maps booleans to have a question mark
            case (#bool(b)) ?(Bool.toText(b) # "?");
            case (_) null;
        };
    },
);
```

Any thoughts/concerns are welcome, still a work in progress.
Also adding this has made me realize a few design mistakes I made in the current version, so Im going to be making some breaking changes:
- #_null, #_func, etc.. will change to #null_, #func_, etc... because apparently that is the correct way to escape reserved words in motoko
- `TransparencyState = { #opaque; #transparent(t) }` is not only confusing but annoying to deal with. Its really just something that should live at the encoding level. And plus there isnt really much support or usage of #opaque right now, so im going to be removing or changing that
- #opt(?Value) is changing to #opt(Value) because #opt(#null_) is the same as #opt(null). 


I have other priorities this week so Im not sure when ill get time to work on it more. But this seems to be in a good state to try

**Comment by fermartz** [comment]
@Gekctek thank you so much. 

I will try it and send you feedback.

🙌

**Comment by Gekctek** [comment]
I have added the toText to Values and Types. 

Apparently the build is failing but thats a MOPS regression it seems

**Comment by Gekctek** [comment]
now under MOPS package `candid@1.0.0`

**Pull request merged**
